### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Arch-Noize** [Arch-Noize/ruby-capstone#35]
We are a team of two people, and we've divided the work evenly from our point of view. Here's the link to our project:
https://github.com/Arch-Noize/ruby-capstone/projects/2

@lilskyex0x is designated as Team Member #1, @Arch-Noize is designated as Team Member #2, and bot are divided to work on the tasks of Team Member #3

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Arch-Noize and @lilskyex0x,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well-assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] There seems to be a mix up in the description of this task. It is intended for Book class creation, but has description for `schema.sql` task.

  ![image](https://github.com/Arch-Noize/ruby-capstone/assets/36542986/523d899a-f7dd-41a1-ab39-0b0103dcac97)

- [ ] Kindly remove these other dummy task templates.

  ![image](https://github.com/Arch-Noize/ruby-capstone/assets/36542986/187b5c2d-9587-4f5c-b9c9-a3a293926906)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ridwanediallo** [comment]
# STATUS: APPROVED 🟢
## Hi team, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Well done implementing the requested changes. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
